### ISSUE TITLE
Incorrect threat range S-300 launcher

### ISSUE THREAD

**Issue by adamdoda** [pydcs/dcs#108]
Threat range is 120000 (120km, 64nm) and it should be 40nm.
Is this an exported data and incorrect in DCS itself, could we fix it?

_vehicles.py / SAM_SA_10_S_300PS_LN_5P85C, SAM_SA_10_S_300PS_LN_5P85D_

**Comment by rp-** [comment]
yes this is exported from DCS and changing it in pydcs wouldn't have any effect on DCS.
I just exported them to so algorithms/scripts can make air defense coverage or for whatever they are useful.

**Comment by adamdoda** [comment]
Ok thanks than I solve this in our code. I know it wouldn't have any effect on DCS, I have to display the correct value.
