### ISSUE TITLE
Support for 2.7 weather options

### ISSUE THREAD

**Issue by DanAlbert** [pydcs/dcs#118]
Unless you're planning to do this in the next day or so go ahead and assign to me :) Looking to update Liberation to take advantage of this so I'll send a PR this weekend if support hasn't landed yet.

(I haven't looked at this at all yet, so unclear if weather is the only thing that will be needed for 2.7)

**Comment by rp-** [comment]
I just did a quick glance at the mission file and weather section and it seems they really just placed a `clouds` object there with basically the preset, and 2 or 3 other values.
I was expecting the mission file had already the advanced weather stuff, but this looks like the whole thing will be obsolete once we get the real new weather system(in two 2 weeks...).

I'm not sure I have the time to add this, till the weekend, so please go ahead.

**Comment by DanAlbert** [comment]
Sounds good. I'll send you something this weekend if not sooner.

**Comment by Khopa** [comment]
For reference, someone sent this to me : https://www.reddit.com/r/hoggit/comments/mqzv11/hidden_clouds_settings/

There are a few disabled presets, and settings giving an idea of what the future system might be.
But unless we know the miz format, this won't exactly help i guess.

**Comment by DanAlbert** [comment]
> I just did a quick glance at the mission file and weather section and it seems they really just placed a clouds object there with basically the preset, and 2 or 3 other values.

Experimented with a few of these in the ME, and it looks like when using a preset the density is always 0, thickness is always 200, precipitation is always 0 (even for rainy presets), and base is configurable.

I think for now (ED have said that this is going to change again in the future, and it sounds like in the not too distant future) I'll keep it simple and just add the serialization/deserialization for the `preset` field as well as force the other values when serializing. Keeps the API more or less the way it is.

I'll also enumerate all the valid presets so that clients don't need to do that themselves.

**Comment by DanAlbert** [comment]
Although one more detail here is that the configurable base does have a min/max value per preset. It's specified in the file @Khopa linked, so I'll write an extractor for that.
