### ISSUE TITLE
Load mission fails

### ISSUE THREAD

**Issue by adamdoda** [pydcs/dcs#121]
Load mission is not working.
Add one plane save mission, try to load it with pydcs, it will fail.

`  File "tauntaun_live_editor\dcs\dcs\point.py", line 48, in load_from_dict
KeyError: 'name'`

**Comment by ColinM9991** [comment]
Are you saving and loading from within pydcs or are you saving the mission via the in-game editor at any point?

**Comment by adamdoda** [comment]
I saved a new mission with DCS 2.7.0 in-game editor.

**Comment by ColinM9991** [comment]
You'll want to install this package directly from GitHub in that case as it doesn't seem like an update has been pushed yet for 2.7 support.

You can do this by first uninstalling pydcs from your Python project.
`pip uninstall pydcs`

Then install directly from a GitHub repository
`pip install git+https://github.com/pydcs/dcs.git`

**Comment by adamdoda** [comment]
https://github.com/UOAF/project-tauntaun
I use it directly as a submodule.

**Comment by rp-** [comment]
fixed: f8922b26ac6b0b37a534082bd0647a42a5daafdf

**Comment by adamdoda** [comment]
Thanks
