### ISSUE TITLE
onboard_num failing to parse alphanumeric assignments

### ISSUE THREAD

**Issue by ColinM9991** [pydcs/dcs#122]
`onboard_num` is a string in the mission file but is converted to an integer when interpreted by this module.

This causes the following exception when a mission is loaded that contains a unit with an alphanumerical tail number
>ValueError: invalid literal for int() with base 10: 'E3A'

Is this an intentional design choice?

**Comment by rp-** [comment]
It kinda was/is see #112 
I was not aware that onboard_num might be an alphanum, I mean it is called onboard_**num** for a reason I thought, also the dcs editor only uses numbers.

**Comment by ColinM9991** [comment]
> It kinda was/is see #112
> I was not aware that onboard_num might be an alphanum, I mean it is called onboard_**num** for a reason I thought, also the dcs editor only uses numbers.

I noticed that just after raising this as it appears as a Google search result for `onboard_num`.

I'll inspect the mission later to see how the value is represented in the editor.

The following page suggests that `onboard_num` is also a string https://wiki.hoggitworld.com/view/DCS_func_addGroup

**Comment by rp-** [comment]
Yeah it is a string, but I just wasn't sure if it is a string by accident, I mean if it is common to have alpha-characters in there I'm totally fine to remove the int restriction. I just thought it should be a number

**Comment by ColinM9991** [comment]
I've just had a look in the mission editor which uses a free form textbox for the tail/`onboard_num` value

![image](https://user-images.githubusercontent.com/57466042/115159856-22d2b800-a08d-11eb-90f8-b4c061e40f63.png)
