### ISSUE TITLE
Plane name indexing behavior in String class

### ISSUE THREAD

**Issue by ColinM9991** [pydcs/dcs#127]
The translation.py file holds a `String` class which indexes the translation dictionary to return the value matched with a given key. There is a problem however when a tail plate is already reserved and a warning message is generated in coalition.py line 165 whereby the `plane.name` property tries to index the `translation` dictionary with the `id` that is the actual unit name, not the DictKey name. The translation dictionary, on the other hand, contains values from the l10n/DEFAULT/dictionary file, none of which are unit names.

This results in the following exception
>File "C:\source\DiscordBot\venv\lib\site-packages\dcs\mission.py", line 374, in load_file
>    status += self.coalition[col_name].load_from_dict(self, imp_mission["coalition"][col_name])
>File C:\source\DiscordBot\venv\lib\site-packages\dcs\coalition.py", line 165, in load_from_dict
>    msg = "{c} Plane '{p}' already using tail number: {t}".format(
>File "C:\source\DiscordBot\venv\lib\site-packages\dcs\translation.py", line 24, in __str__
>    return self.str('DEFAULT')
>File "C:\source\DiscordBot\venv\lib\site-packages\dcs\translation.py", line 19, in str
>    return self.translation.strings[lang][self.id]
>KeyError: 'USAEF F-15C 1'

I can submit a PR to return the `id` in a scenario where the `translation` is defined but the key does not exist, if that is a desired behavior. I have tested this locally and can confirm it works.

```python
def str(self, lang='DEFAULT'):
    if self.translation:
        if self.translation.has_string(self.id):
            return self.translation.strings[lang][self.id]
        else:
            return self.id

    return ""
```

**Comment by adamdoda** [comment]
Related #128 #129.

**Comment by ColinM9991** [comment]
Closing as it's being tracked already with a better solution
