### ISSUE TITLE
How comes that F5 is not flyable?

### ISSUE THREAD

**Issue by shdwp** [pydcs/dcs#13]
`F_5E_3` is not `flyable`. Changing it manually works just fine.

If this was exported automatically, how comes?

**Comment by shdwp** [comment]
Thanks a lot.

**Comment by shdwp** [comment]
Hmm, I'd rather leave this open until then, just for me to not forget to fetch the changes.

**Comment by rp-** [comment]
yeah I just recently added this exception, if you set client or player on a unit that is not flyable.
I thought my data is correct.

**Comment by shdwp** [comment]
Okay, no problem. I'll disable the exception temporarily in my copy and wait till new export.

**Comment by rp-** [comment]
updated the data with the current dcs open beta
