### ISSUE TITLE
Pydcs generated classes names depends on "name" instead of "ID"

### ISSUE THREAD

**Issue by Khopa** [pydcs/dcs#144]
Hello, 

Since 2.7.0 openbeta was released, ED has taken a new habit of changing units & weapons names every few patches.

This affect pydcs in a bad way, as classes names for planes/vehicles/ships and weapons are derived from this "name" property.

For example, in DCS 2.6, if you wanted to put a Panzer IV in a mission with pydcs, you'd have to use the class : **MT_Pz_Kpfw_IV_Ausf_H**
With DCS version 2.7.0.4625 version, it changed to : **MT_PzIV_H**
And now after today's patch (2.7.1.6436 https://github.com/pydcs/dcs/pull/143), it is : **Tk_PzIV_H**

This is painful for library users that rely on these classes, as this cause maintenance pain.

***

So i can't help but think that it would be better for everyone if pydcs units classes names were generated from the "ID" instead of the "name" of the units. Since the id is what ends up in the miz files, ED can't change it without breaking existing missions, so it would be very unlikely to ever change. So if we were using that,  the pydcs API will also be more stable in the future.

Do you think this would cause issue, should the export script be changed to use IDs instead of name ?

**Comment by rp-** [comment]
Yes makes sense to use ID.
I guess names were more informative, but if ED thinks changing them every second version, it doesn't make sense to use them.
