### ISSUE TITLE
drop Python 3.6 support?

### ISSUE THREAD

**Issue by DanAlbert** [pydcs/dcs#162]
I mistakenly use something from 3.7+ just about every time I make a change here. Any idea if there are any users still depending on 3.6 support? For us (Liberation), all we care about is 3.9 (and in a few months we'll only care about 3.10), but idk what other users need.

Supporting 3.6 keeps us from using (among other, less interesting things):

* `from __future__ import annotations` (allows using non-quoted type names in type annotations for circular imports, factory classmethods, comparators, etc)
* dataclasses

Dropping 3.6 is the only really interesting one (to me at least) at the moment since those two features are the ones I always expect to be able to use until the github checks say no :) 3.9 is nice because it lets you use `list[...]` instead of importing `List` from `typing` (and same for all the other built in types), but that's pretty minor.

If there are users that still depend on 3.6 support this isn't a big deal so can just be closed, but if not it'd be nice to move forward, expecially since 3.10 will bring some basic type contracts that can presumably improve some of the APIs.

**Comment by rp-** [comment]
I'm pretty sure everyon could easily upgrade to 3.7 or even 3.9.
So I have no objections to go to 3.7
