### ISSUE TITLE
can't set AI comm frequency for aircraft without preset channel support

### ISSUE THREAD

**Issue by DanAlbert** [pydcs/dcs#175]
https://github.com/pydcs/dcs/pull/173 introduced a bug in `FlyingGroup.set_frequency` for any aircraft without preset channel support. That function is used to set the AI's comm frequency, but it also tries to set channel 1 to the same frequency. That function now raises when used for aircraft without preset channel support. The new error needs to be suppressed there.

**Comment by magwo** [comment]
Roger, will take a look.
