### ISSUE TITLE
Get this error when trying to pass turn

### ISSUE THREAD

**Issue by SpeedyE420** [pydcs/dcs#18]
INFO:root:DCS Libration None
INFO:root:Using C:\Users\eelmo\Saved Games\DCS.openbeta as userdata folder
INFO:root:Generating Convoy Strike (regular)
ERROR:root:Didn't find ground position (Point(-239298.02076082907, 881856.2498073743))!
INFO:root:airgen: <class 'dcs.helicopters.Ka_50'> for 2 at unit <dcs.unitgroup.StaticGroup object at 0x00B65B90>
INFO:root:Loaded overridden payload for <class 'dcs.helicopters.Ka_50'> - 12x9A4172, 40xS-8 for task <class 'dcs.task.CAS'>
INFO:root:armorgen: <class 'dcs.vehicles.Unarmed.Transport_Ural_375'> for 0
INFO:root:armorgen: <class 'dcs.vehicles.Unarmed.Transport_Ural_375'> for 0
INFO:root:armorgen: <class 'dcs.vehicles.Unarmed.Transport_Ural_375'> for 0
INFO:root:armorgen: <class 'dcs.vehicles.Unarmed.Transport_Ural_375'> for 0
INFO:root:armorgen: <class 'dcs.vehicles.Unarmed.Transport_Ural_375'> for 0
INFO:root:armorgen: <class 'dcs.vehicles.Armor.APC_BTR_80'> for 0
INFO:root:armorgen: <class 'dcs.vehicles.Armor.APC_BTR_80'> for 0
INFO:root:armorgen: <class 'dcs.vehicles.Armor.APC_BTR_80'> for 0
INFO:root:generated object identifier comms|32|6|1 with mission id 13
INFO:root:generated object identifier farp|32|7|1 with mission id 14
INFO:root:generated object identifier farp|32|7|2 with mission id 15
INFO:root:generated object identifier farp|32|7|3 with mission id 16
INFO:root:generated object identifier farp|32|7|4 with mission id 17
INFO:root:generated object identifier farp|32|7|5 with mission id 18
INFO:root:generated object identifier farp|32|7|6 with mission id 19
INFO:root:generated object identifier farp|32|7|7 with mission id 20
INFO:root:generated object identifier farp|32|7|8 with mission id 21
INFO:root:generated object identifier farp|32|7|9 with mission id 22
INFO:root:generated object identifier power|32|8|1 with mission id 23
INFO:root:generated object identifier power|32|8|2 with mission id 24
INFO:root:generated object identifier power|32|8|3 with mission id 25
INFO:root:generated object identifier power|32|8|4 with mission id 26
INFO:root:generated object identifier power|32|8|5 with mission id 27
INFO:root:generated object identifier farp|32|9|1 with mission id 28
INFO:root:generated object identifier farp|32|9|2 with mission id 29
INFO:root:generated object identifier farp|32|9|3 with mission id 30
INFO:root:generated object identifier farp|32|9|4 with mission id 31
INFO:root:generated object identifier farp|32|9|5 with mission id 32
INFO:root:generated object identifier farp|32|9|6 with mission id 33
INFO:root:generated object identifier farp|32|9|7 with mission id 34
INFO:root:generated object identifier farp|32|9|8 with mission id 35
INFO:root:generated object identifier farp|32|9|9 with mission id 36
INFO:root:generated object identifier warehouse|32|10|1 with mission id 37
INFO:root:generated object identifier warehouse|32|10|2 with mission id 38
INFO:root:generated object identifier warehouse|32|10|3 with mission id 39
INFO:root:generated object identifier warehouse|32|10|4 with mission id 40
INFO:root:generated defense object identifier aa|32|11|1 with mission id 41
INFO:root:time - 2018-05-25 15:00:00, slot - (9, 18), night skipped - False
INFO:root:generated weather 3
INFO:root:Generating Convoy Strike (quick)
ERROR:root:Didn't find ground position (Point(-239298.02076082907, 881856.2498073743))!
INFO:root:airgen: <class 'dcs.helicopters.Ka_50'> for 2 at unit <dcs.unitgroup.StaticGroup object at 0x1222DCB0>
INFO:root:Loaded overridden payload for <class 'dcs.helicopters.Ka_50'> - 12x9A4172, 40xS-8 for task <class 'dcs.task.CAS'>
INFO:root:armorgen: <class 'dcs.vehicles.Unarmed.Transport_Ural_375'> for 0
INFO:root:armorgen: <class 'dcs.vehicles.Unarmed.Transport_Ural_375'> for 0
INFO:root:armorgen: <class 'dcs.vehicles.Unarmed.Transport_Ural_375'> for 0
INFO:root:armorgen: <class 'dcs.vehicles.Unarmed.Transport_Ural_375'> for 0
INFO:root:armorgen: <class 'dcs.vehicles.Unarmed.Transport_Ural_375'> for 0
INFO:root:armorgen: <class 'dcs.vehicles.Armor.APC_BTR_80'> for 0
INFO:root:armorgen: <class 'dcs.vehicles.Armor.APC_BTR_80'> for 0
INFO:root:armorgen: <class 'dcs.vehicles.Armor.APC_BTR_80'> for 0
INFO:root:generated object identifier comms|32|6|1 with mission id 13
INFO:root:generated object identifier farp|32|7|1 with mission id 14
INFO:root:generated object identifier farp|32|7|2 with mission id 15
INFO:root:generated object identifier farp|32|7|3 with mission id 16
INFO:root:generated object identifier farp|32|7|4 with mission id 17
INFO:root:generated object identifier farp|32|7|5 with mission id 18
INFO:root:generated object identifier farp|32|7|6 with mission id 19
INFO:root:generated object identifier farp|32|7|7 with mission id 20
INFO:root:generated object identifier farp|32|7|8 with mission id 21
INFO:root:generated object identifier farp|32|7|9 with mission id 22
INFO:root:generated object identifier power|32|8|1 with mission id 23
INFO:root:generated object identifier power|32|8|2 with mission id 24
INFO:root:generated object identifier power|32|8|3 with mission id 25
INFO:root:generated object identifier power|32|8|4 with mission id 26
INFO:root:generated object identifier power|32|8|5 with mission id 27
INFO:root:generated object identifier farp|32|9|1 with mission id 28
INFO:root:generated object identifier farp|32|9|2 with mission id 29
INFO:root:generated object identifier farp|32|9|3 with mission id 30
INFO:root:generated object identifier farp|32|9|4 with mission id 31
INFO:root:generated object identifier farp|32|9|5 with mission id 32
INFO:root:generated object identifier farp|32|9|6 with mission id 33
INFO:root:generated object identifier farp|32|9|7 with mission id 34
INFO:root:generated object identifier farp|32|9|8 with mission id 35
INFO:root:generated object identifier farp|32|9|9 with mission id 36
INFO:root:generated object identifier warehouse|32|10|1 with mission id 37
INFO:root:generated object identifier warehouse|32|10|2 with mission id 38
INFO:root:generated object identifier warehouse|32|10|3 with mission id 39
INFO:root:generated object identifier warehouse|32|10|4 with mission id 40
INFO:root:generated defense object identifier aa|32|11|1 with mission id 41
INFO:root:debriefing: found dead unit unit|0|2|Ural-375| Unit #1 (3, <class 'dcs.vehicles.Unarmed.Transport_Ural_375'>)
INFO:root:debriefing: found dead unit unit|0|3|Ural-375| Unit #1 (4, <class 'dcs.vehicles.Unarmed.Transport_Ural_375'>)
INFO:root:debriefing: found dead unit unit|0|4|Ural-375| Unit #1 (5, <class 'dcs.vehicles.Unarmed.Transport_Ural_375'>)
INFO:root:debriefing: found dead unit unit|0|5|Ural-375| Unit #1 (6, <class 'dcs.vehicles.Unarmed.Transport_Ural_375'>)
INFO:root:debriefing: found dead unit unit|0|6|Ural-375| Unit #1 (7, <class 'dcs.vehicles.Unarmed.Transport_Ural_375'>)
INFO:root:debriefing: found dead unit unit|0|7|BTR-80| Unit #1 (8, <class 'dcs.vehicles.Armor.APC_BTR_80'>)
INFO:root:debriefing: found dead unit unit|0|8|BTR-80| Unit #1 (9, <class 'dcs.vehicles.Armor.APC_BTR_80'>)
INFO:root:debriefing: found dead unit unit|0|9|BTR-80| Unit #1 (10, <class 'dcs.vehicles.Armor.APC_BTR_80'>)
INFO:root:debriefing: unsatistied ids: []
INFO:root:Finishing event Convoy Strike
INFO:root:base <theater.base.Base object at 0x14724530> commit losses {}
INFO:root:base <theater.base.Base object at 0x14724510> commit losses {<class 'dcs.vehicles.Unarmed.Transport_Ural_375'>: 5, <class 'dcs.vehicles.Armor.APC_BTR_80'>: 3}
INFO:root:Pass turn
INFO:root:Commision Beslan: {<class 'dcs.vehicles.Armor.MBT_T_55'>: 3}
INFO:root:Commision Beslan: {<class 'dcs.planes.AJS37'>: 1}
INFO:root:Commision Nalchik: {<class 'dcs.planes.Su_25'>: 1}
INFO:root:Commision Mozdok: {<class 'dcs.planes.L_39ZA'>: 1}
INFO:root:Commision Kutaisi: {<class 'dcs.planes.Su_25T'>: 1}
INFO:root:Commision Kutaisi: {<class 'dcs.planes.M_2000C'>: 2}
INFO:root:Commision Senaki: {<class 'dcs.planes.Su_25T'>: 1}
INFO:root:Commision Kobuleti: {<class 'dcs.planes.L_39ZA'>: 1}
INFO:root:Commision Gelendzhik: {<class 'dcs.planes.Su_25T'>: 1}
INFO:root:<theater.base.Base object at 0x12243AF0> for <class 'dcs.task.CAP'> (0): {<class 'dcs.planes.M_2000C'>: 2}
INFO:root:Generating Air Intercept (regular)
INFO:root:airgen: <class 'dcs.planes.An_26B'> for 0 at 3300 at 550
INFO:root:airgen: <class 'dcs.planes.M_2000C'> for 0 at 3600 at 550
INFO:root:Loaded overridden payload for <class 'dcs.planes.M_2000C'> - Combat Air Patrol for task <class 'dcs.task.CAP'>
INFO:root:airgen: <class 'dcs.planes.F_14B'> for 2 at <class 'dcs.terrain.caucasus.Soganlug'>
INFO:root:Loaded overridden payload for <class 'dcs.planes.F_14B'> - AIM-54A-MK47*4, AIM-7M*2, AIM-9M*2, XT*2 for task <class 'dcs.task.CAP'>
INFO:root:airgen: <class 'dcs.planes.FA_18C_hornet'> for 2 at <class 'dcs.terrain.caucasus.Soganlug'>
INFO:root:Loaded overridden payload for <class 'dcs.planes.FA_18C_hornet'> - AIM-120*4,AIM-9*2,AIM-7*2,Fuel for task <class 'dcs.task.CAP'>
INFO:root:generated dead object identifier warehouse|25|33|1 with mission id 8
INFO:root:generated object identifier warehouse|25|33|2 with mission id 9
INFO:root:generated dead object identifier warehouse|25|33|3 with mission id 10
INFO:root:generated object identifier warehouse|25|33|4 with mission id 11
INFO:root:generated dead object identifier fob|25|34|1 with mission id 12
INFO:root:generated object identifier fob|25|34|2 with mission id 13
INFO:root:generated object identifier fob|25|34|3 with mission id 14
INFO:root:generated object identifier fob|25|34|4 with mission id 15
INFO:root:generated object identifier fob|25|34|5 with mission id 16
INFO:root:generated object identifier fob|25|34|6 with mission id 17
INFO:root:generated dead object identifier farp|25|35|1 with mission id 18
INFO:root:generated object identifier farp|25|35|2 with mission id 19
INFO:root:generated dead object identifier farp|25|35|3 with mission id 20
INFO:root:generated dead object identifier farp|25|35|4 with mission id 21
INFO:root:generated dead object identifier farp|25|35|5 with mission id 22
INFO:root:generated dead object identifier farp|25|35|6 with mission id 23
INFO:root:generated object identifier farp|25|35|7 with mission id 24
INFO:root:generated object identifier farp|25|35|8 with mission id 25
INFO:root:generated object identifier farp|25|35|9 with mission id 26
INFO:root:generated dead object identifier fob|25|36|1 with mission id 27
INFO:root:generated object identifier fob|25|36|2 with mission id 28
INFO:root:generated object identifier fob|25|36|3 with mission id 29
INFO:root:generated object identifier fob|25|36|4 with mission id 30
INFO:root:generated object identifier fob|25|36|5 with mission id 31
INFO:root:generated object identifier fob|25|36|6 with mission id 32
INFO:root:generated defense object identifier aa|25|37|1 with mission id 33
INFO:root:time - 2018-05-25 19:00:00, slot - (18, 20), night skipped - False
INFO:root:generated weather 4
INFO:root:Generating Air Intercept (quick)
INFO:root:airgen: <class 'dcs.planes.An_26B'> for 0 at 3300 at 550
INFO:root:airgen: <class 'dcs.planes.M_2000C'> for 0 at 3600 at 550
INFO:root:Loaded overridden payload for <class 'dcs.planes.M_2000C'> - Combat Air Patrol for task <class 'dcs.task.CAP'>
INFO:root:airgen: <class 'dcs.planes.F_14B'> for 2 at 3900 at 550
INFO:root:Loaded overridden payload for <class 'dcs.planes.F_14B'> - AIM-54A-MK47*4, AIM-7M*2, AIM-9M*2, XT*2 for task <class 'dcs.task.CAP'>
INFO:root:airgen: <class 'dcs.planes.FA_18C_hornet'> for 2 at 4200 at 550
INFO:root:Loaded overridden payload for <class 'dcs.planes.FA_18C_hornet'> - AIM-120*4,AIM-9*2,AIM-7*2,Fuel for task <class 'dcs.task.CAP'>
INFO:root:generated dead object identifier warehouse|25|33|1 with mission id 8
INFO:root:generated object identifier warehouse|25|33|2 with mission id 9
INFO:root:generated dead object identifier warehouse|25|33|3 with mission id 10
INFO:root:generated object identifier warehouse|25|33|4 with mission id 11
INFO:root:generated dead object identifier fob|25|34|1 with mission id 12
INFO:root:generated object identifier fob|25|34|2 with mission id 13
INFO:root:generated object identifier fob|25|34|3 with mission id 14
INFO:root:generated object identifier fob|25|34|4 with mission id 15
INFO:root:generated object identifier fob|25|34|5 with mission id 16
INFO:root:generated object identifier fob|25|34|6 with mission id 17
INFO:root:generated dead object identifier farp|25|35|1 with mission id 18
INFO:root:generated object identifier farp|25|35|2 with mission id 19
INFO:root:generated dead object identifier farp|25|35|3 with mission id 20
INFO:root:generated dead object identifier farp|25|35|4 with mission id 21
INFO:root:generated dead object identifier farp|25|35|5 with mission id 22
INFO:root:generated dead object identifier farp|25|35|6 with mission id 23
INFO:root:generated object identifier farp|25|35|7 with mission id 24
INFO:root:generated object identifier farp|25|35|8 with mission id 25
INFO:root:generated object identifier farp|25|35|9 with mission id 26
INFO:root:generated dead object identifier fob|25|36|1 with mission id 27
INFO:root:generated object identifier fob|25|36|2 with mission id 28
INFO:root:generated object identifier fob|25|36|3 with mission id 29
INFO:root:generated object identifier fob|25|36|4 with mission id 30
INFO:root:generated object identifier fob|25|36|5 with mission id 31
INFO:root:generated object identifier fob|25|36|6 with mission id 32
INFO:root:generated defense object identifier aa|25|37|1 with mission id 33
INFO:root:debriefing: found dead unit unit|0|23|An-26B| Pilot #1 (1, <class 'dcs.planes.An_26B'>)
INFO:root:debriefing: found dead unit unit|0|24|M-2000C| Pilot #1 (2, <class 'dcs.planes.M_2000C'>)
INFO:root:debriefing: found dead unit unit|0|24|M-2000C| Pilot #2 (3, <class 'dcs.planes.M_2000C'>)
INFO:root:debriefing: found dead static warehouse|25|33|1 (9)
INFO:root:debriefing: found dead static warehouse|25|33|3 (11)
INFO:root:debriefing: found dead static fob|25|34|1 (13)
INFO:root:debriefing: found dead static farp|25|35|1 (19)
INFO:root:debriefing: found dead static farp|25|35|3 (21)
INFO:root:debriefing: found dead static farp|25|35|4 (22)
INFO:root:debriefing: found dead static farp|25|35|5 (23)
INFO:root:debriefing: found dead static farp|25|35|6 (24)
INFO:root:debriefing: found dead static fob|25|36|1 (28)
INFO:root:debriefing: unsatistied ids: []
INFO:root:Finishing event Air Intercept
INFO:root:base <theater.base.Base object at 0x14724530> commit losses {}
INFO:root:base <theater.base.Base object at 0x12243AF0> commit losses {<class 'dcs.planes.An_26B'>: 1, <class 'dcs.planes.M_2000C'>: 2}
INFO:root:Pass turn
INFO:root:Commision Nalchik: {<class 'dcs.planes.Su_25T'>: 1}
INFO:root:Commision Mozdok: {<class 'dcs.planes.Su_25'>: 1}
INFO:root:Commision Kutaisi: {<class 'dcs.planes.MiG_23MLD'>: 2}
INFO:root:Commision Kobuleti: {<class 'dcs.planes.Su_25'>: 1}
INFO:root:Commision Gelendzhik: {<class 'dcs.planes.L_39ZA'>: 1}
INFO:root:Pass turn
ERROR:root:<class 'ValueError'>
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1702, in __call__
  File "ui\mainmenu.py", line 36, in pass_turn
  File "ui\mainmenu.py", line 29, in display
  File "ui\overviewcanvas.py", line 590, in update
  File "ui\overviewcanvas.py", line 252, in draw
  File "ui\overviewcanvas.py", line 312, in draw_map
  File "ui\overviewcanvas.py", line 331, in draw_bases
ValueError: negative radius
INFO:root:Pass turn
ERROR:root:<class 'ValueError'>
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1702, in __call__
  File "ui\mainmenu.py", line 36, in pass_turn
  File "ui\mainmenu.py", line 29, in display
  File "ui\overviewcanvas.py", line 590, in update
  File "ui\overviewcanvas.py", line 252, in draw
  File "ui\overviewcanvas.py", line 312, in draw_map
  File "ui\overviewcanvas.py", line 331, in draw_bases
ValueError: negative radius

**Comment by rp-** [comment]
the stacktrace looks like the error occurs in dcs liberation, which i'm not directly involved, please add you issue there: https://github.com/shdwp/dcs_liberation
