### ISSUE TITLE
Cannot Find ID of Fujairah Intl, though its listed as #7. Here is my custom file below -Bold Names are Accidental - not bolded in my actual file

### ISSUE THREAD

**Issue by Darkxv** [pydcs/dcs#193]
A recustomization of "The Scenic Route"

The Error I get is --> KeyError: 'Cannot find ControlPoint with ID 7'

---
name: Persian Gulf - Custom
theater: Persian Gulf
authors: Fuzzle
description: <p>A lightweight naval campaign involving a US Navy carrier group pushing across the coast of Iran. <strong>Note that the ground units purchased on turn zero must sustain you until you've taken the first hostile FOB. The starting point does not have a factory to simulate a Marine Expeditionary Force deploying from the carrier group.</strong></p><p><strong>Backstory:</strong> Iran has declared war on all US forces in the Gulf resulting in all local allies withdrawing their support for American troops. A lone carrier group must pacify the southern coast of Iran and hold out until backup can arrive lest the US and her interests be ejected from the region permanently.</p>
version: 9.1
recommended_player_faction: Bluefor Modern
recommended_enemy_faction: Iran 2015
miz: Persian_Gulf_custom.miz
performance: 1
recommended_start_date: 2005-04-26
squadrons:
  # Fujairah Intl
  7:
    - primary: Refueling
      aircraft:
        - KC-135 Stratotanker MPRS
    - primary: Refueling
      aircraft:
        - KC-135 Stratotanker  
    - primary: AEW&C
      aircraft:
        - E-3A
    - primary: Transport
      secondary: any
      aircraft:
        - C-130
    - primary: Strike
      secondary: any
      aircraft:
        - F-16CM Fighting Falcon (Block 50)
    - primary: BAI
      secondary: air-to-ground
      aircraft:
        - A-10C Thunderbolt II (Suite 7)
    - primary: BAI
      secondary: air-to-ground
      aircraft:
        - A-10C Thunderbolt II (Suite 3)
    - primary: BARCAP
      secondary: any
      aircraft:
        - JF-17 Thunder
    - primary: BARCAP
      aircraft:
        - MiG-23MLD Flogger-K
    - primary: BAI
      secondary: air-to-ground
      aircraft:
        - Ka-50 Hokum
    - primary: Strike
      secondary: any
      aircraft:
        - AJS-37 Viggen
    - primary: Strike
      secondary: air-to-ground
      aircraft:
        - B-52H Stratofortress
    - primary: Strike
      secondary: air-to-ground
      aircraft:
        - B-1B Lancer
    - primary: Strike
      secondary: any
      aircraft:
        - Mirage 2000C
  #BLUFOR CVN
  Naval-1:
    - primary: BARCAP
      secondary: air-to-air
      aircraft:
        - VF-143
    - primary: SEAD
      secondary: any
      aircraft:
        - VFA-113
    - primary: BAI
      secondary: any
      aircraft:
        - VMFA-251
    - primary: AEW&C
      aircraft:
        - VAW-125
    - primary: Refueling
      aircraft:
        - VS-35 (Tanker)
    - primary: Anti-ship
      secondary: air-to-ground
      aircraft:
        - VS-35
    - primary: Transport
      aircraft:
        - HSM-40
  # BLUFOR LHA
  Naval-2:
    - primary: BAI
      secondary: air-to-ground
      aircraft:
        - VMA-223
    - primary: Transport
      secondary: air-to-ground
      aircraft:
        - HMLA-169 (UH-1H)
    - primary: CAS
      secondary: air-to-ground
      aircraft:
        - HMLA-169 (AH-1W)
  # BLUFOR Start FOB
  FOB Bandar-e-Jask:
    - primary: Transport
      secondary: air-to-ground
      aircraft:
        - HMLA-269 (UH-1H)
    - primary: CAS
      secondary: air-to-ground
      aircraft:
        - HMLA-269 (AH-1W)
  # OPFOR CVN
  Naval-3:
    - primary: BARCAP
      secondary: any
    - primary: Strike
      secondary: any
    - primary: BAI
      secondary: any
    - primary: Refueling
  # Kish Intl
  24:
    - primary: AEW&C
      aircraft:
        - A-50
    - primary: Refueling
      aircraft:
        - IL-78M
    - primary: Transport
      aircraft:
        - IL-78MD
    - primary: BARCAP
      secondary: any
      aircraft:
        - F-14A Tomcat (Block 135-GR Late)
    - primary: Strike
      secondary: air-to-ground
      aircraft:
        - Su-24MK Fencer-D
    - primary: BARCAP
      secondary: any
      aircraft:
        - F-4E Phantom II
  # Havadarya
  9:
    - primary: BARCAP
      secondary: any
      aircraft:
      - F-4E Phantom II
    - primary: CAS
      secondary: air-to-ground
      aircraft:
      - Su-25 Frogfoot
  # Bandar Abbas Intl
  2:
    - primary: TARCAP
      secondary: any
      aircraft:
        - F-5E Tiger II
    - primary: BARCAP
      secondary: air-to-ground
      aircraft:
        - MiG-29A Fulcrum-A
    - primary: Strike
      secondary: air-to-ground
      aircraft:
        - Su-24MK
    - primary: BARCAP
      secondary: air-to-ground
      aircraft:
        - F-4E Phantom II
  # OPFOR First FOB
  FOB Seerik:
    - primary: CAS
      secondary: air-to-ground
      aircraft:
        - Mi-24V Hind-E
  # OPFOR Second FOB
  FOB Kohnehshahr:
    - primary: CAS
      secondary: air-to-ground
      aircraft:
        - Mi-24V Hind-F
  # OPFOR Third FOB
  FOB Khvosh:
    - primary: CAS
      secondary: air-to-ground
      aircraft:
        - Mi-28N Havoc
  # OPFOR Last FOB
  FOB Charak:
    - primary: CAS
      secondary: air-to-ground
      aircraft:
        - Mi-28N Havoc

**Comment by DanAlbert** [comment]
Idk why this was reported here. pydcs clearly has this airport so it's on the liberation side.

**Comment by Darkxv** [comment]
Im unsure where to go with it. that's why I reported it here. Can you help me figure out who I can bring this up with that can help me get this figured out?

**Comment by DanAlbert** [comment]
There's a "file bug" button in the help menu in liberation, fwiw. Looks like you did get one filed there. This should be closed.
