### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by wrycu** [pydcs/dcs#20]
It looks like there has been a substantial number of commits to this repo since the last release in November of 2017. 

Please build and upload to pypi a new version of this library so we can enjoy all of the hard work done by you fine code authors without having to clone the repo and build the package ourselves.

**Comment by rp-** [comment]
did a new release and will try to do releases more often

**Comment by Khopa** [comment]
Thank you !

**Comment by wrycu** [comment]
Thank you. The library is a godsend 🥇
