### ISSUE TITLE
Important triggers require getValueResourceByKey

### ISSUE THREAD

**Issue by spencershepard** [pydcs/dcs#225]
Interestingly, this will **silently** break triggers in a mission launched as multiplayer, but singleplayer seems to be unaffected.  Opening the mission in the ME also 'fixes' it by adding (getValueResourceByKey.  It looks like the following triggers at minimum from my testing need getValueResourceByKey:

a_out_sound
a_out_sound_g

Additionally, the lua predicate condition needs getValueDictByKey:
c_predicate

https://github.com/pydcs/dcs/commit/9cf6740a3a880f3f9329bef4b6e6557e4eb1239f

Let me know if I can help with testing.  Thanks!

**Comment by rp-** [comment]
merged thanks
