### ISSUE TITLE
terrain export instructions no longer work

### ISSUE THREAD

**Issue by DanAlbert** [pydcs/dcs#230]
[These instructions](https://github.com/pydcs/dcs/issues/36#issuecomment-640748908) no longer work for the latest DCS. I tried doing this for the new Falklands map and got the following error:

```
2022-06-13 01:43:36.729 ALERT   LUACOMMON: Error: GUI Error: [string "./MissionEditor/modules/me_map_window.lua"]:4514: attempt to index global 'MapWindow' (a nil value)
GUI debug.traceback: stack traceback:
	[C]: ?
	[string "./MissionEditor/modules/me_map_window.lua"]:4514: in function 'dumpairportdata'
	[string "./MissionEditor/modules/me_map_window.lua"]:4543: in function 'createAircraft'
	[string "./MissionEditor/modules/me_map_window.lua"]:2270: in function 'onMouseDown'
	[string "./dxgui/bind/NewMapView.lua"]:362: in function 'callback'
	[string "./dxgui/bind/Widget.lua"]:299: in function <[string "./dxgui/bind/Widget.lua"]:298>
```

**Comment by Khopa** [comment]
Hey @DanAlbert ,

If you copied pasted, the  "dumpairportdata" function which is provided the top of the issue, I think this version does not work anymore. 

I don't have access to my DCS PC to test right now, but, IIRC, you just have to change ```MapWindow``` to ```base.MapWindow```, like in I did in the screenshoot from my latest comment, and it should work. ED just changed their import/module structure at some point.

Khopa

**Comment by DanAlbert** [comment]
Interesting. I've done this a few times and never had to do that before. I'll try again at some point.
