### ISSUE TITLE
simplify terrain export?

### ISSUE THREAD

**Issue by DanAlbert** [pydcs/dcs#262]
Terrain exports take a very long time due to needing to manually edit the terrain python files. It's pretty difficult to automate reliably with the current APIs, but this could be made trivial (or at least as trivial as the export process itself) if we're content to break the API a bit.

The things I'd like to drop:

```python
    def anapa_vityazevo(self) -> Airport:
        return self.airports["Anapa-Vityazevo"]

    def krasnodar_center(self) -> Airport:
        return self.airports["Krasnodar-Center"]
```

Each terrain has a function per airfield to return that airfield. This is nice for autocompletion I suppose, but the functionality is trivially available and it makes generating the file difficult.

```python
        self.sochi_adler().unit_zones.append(mapping.Rectangle(-164637.14285714, 461964.28571428,
                                                               -165237.14285714, 462564.28571428, self))
        self.sochi_adler().unit_zones.append(mapping.Rectangle(-162801.42857142, 460978.57142857,
                                                               -163601.42857142, 461778.57142857, self))
        self.sochi_adler().unit_zones.append(mapping.Rectangle(-165514.28571428, 461815.71428571,
                                                               -165914.28571428, 462215.71428571, self))
```

tbh I have no idea what this is or how it was generated. The Caucasus is the only terrain that has these, so we've pretty clearly already given up one whatever this feature is.

```
        self.airports['Anapa-Vityazevo'] = Anapa_Vityazevo(self)
        self.airports['Krasnodar-Center'] = Krasnodar_Center(self)
        self.airports['Novorossiysk'] = Novorossiysk(self)
        self.airports['Krymsk'] = Krymsk(self)
        self.airports['Maykop-Khanskaya'] = Maykop_Khanskaya(self)
        self.airports['Gelendzhik'] = Gelendzhik(self)
        self.airports['Sochi-Adler'] = Sochi_Adler(self)
        self.airports['Krasnodar-Pashkovsky'] = Krasnodar_Pashkovsky(self)
        self.airports['Sukhumi-Babushara'] = Sukhumi_Babushara(self)
        self.airports['Gudauta'] = Gudauta(self)
        self.airports['Batumi'] = Batumi(self)
        self.airports['Senaki-Kolkhi'] = Senaki_Kolkhi(self)
        self.airports['Kobuleti'] = Kobuleti(self)
        self.airports['Kutaisi'] = Kutaisi(self)
        self.airports['Mineralnye Vody'] = Mineralnye_Vody(self)
        self.airports['Nalchik'] = Nalchik(self)
        self.airports['Mozdok'] = Mozdok(self)
        self.airports['Tbilisi-Lochini'] = Tbilisi_Lochini(self)
        self.airports['Soganlug'] = Soganlug(self)
        self.airports['Vaziani'] = Vaziani(self)
        self.airports['Beslan'] = Beslan(self)
```

This block (and the airport definitions themselves) will move into a separate (completely auto-generated) file.

I think something like the following:

```
dcs/terrains/caucasus/
  __init__.py # To keep existing imports working
  airports.py # Auto generated
  projection.py # Auto generated
  terrain.py # Non-automatable data
```

`terrain.py` would have the actual `Terrain` definition in more or less the shape it has now, but the end of the constructor would be something like:

```python
from .airports import ALL_AIRPORTS
self.airports = {a.name: a() for a in ALL_AIRPORTS}
```

@rp- any objections? Terrain exports take a good 20-30 minutes with the current number of maps, and that's only going to get worse with how many maps ED is adding lately. Most of that time is spent putting the files together by hand; the actual export process itself is pretty quick.

**Comment by rp-** [comment]
well, when I started this there were only caucasus and nevada.
So this wasn't that much of a burden, but yeah I agree this is getting cumbersome.

>         self.sochi_adler().unit_zones.append(mapping.Rectangle(-164637.14285714, 461964.28571428,
>                                                                -165237.14285714, 462564.28571428, self))
>        self.sochi_adler().unit_zones.append(mapping.Rectangle(-162801.42857142, 460978.57142857,
>                                                               -163601.42857142, 461778.57142857, self))
>        self.sochi_adler().unit_zones.append(mapping.Rectangle(-165514.28571428, 461815.71428571,
>                                                               -165914.28571428, 462215.71428571, self))

These were meant for tree/object-free zones around airports, so mission generators could automatic place air-defense units there, but this is no more viable, as the zones were exported manually.

Rest of the approach sounds reasonable, to have generated and non generated data split in different files.

**Comment by DanAlbert** [comment]
> These were meant for tree/object-free zones around airports, so mission generators could automatic place air-defense units there, but this is no more viable, as the zones were exported manually.

Oh, we can help with that too. We do that heavily but don't rely on pydcs for it. We could potentially upstream what we have. Right now what we have is a pain in the ass to maintain, but someone is working on generating that data from GIS info. It wouldn't take on quite the same API shape, but it's quite usable for what we do. Rather than a curated list of zones, we have geometries that define the land, the sea, and both of those are masked by "exclusion zones". The exclusion zones are polygons surrounding things like cities, forests, rivers, and mountains. Anywhere in the `land - exclusion` polygon should be a safe spawn location.

**Comment by DanAlbert** [comment]
https://github.com/pydcs/dcs/pull/263 does this. I left the unit zones stuff in. Since that's all manual it wasn't (much) effort to keep, and won't cost anything moving forward.
