### ISSUE TITLE
Update PyPI release

### ISSUE THREAD

**Issue by AGSPhoenix** [pydcs/dcs#274]
The latest version of this library available on PyPI is 0.12.0, released over 2 years ago. It no longer works with at least some modern missions (#207 was preventing me from loading a mission I was working on, for example). The readme still instructs users to install from PyPI, so that broken version is the current default experience for new users.

Please update PyPI with the latest release (and given that that is also approaching 2 years old, a new release or reconsideration of the recommended installation method might be worth considering).

**Comment by rp-** [comment]
Well, the main user of the library is dcs liberation and they use direct git commit to refer.

So I got a bit lazy with releases, also most of the time it is only dcs patch updates, so yes I agree it would make sense to at least release once a month in sync with the dcs release schedule.

**Comment by DanAlbert** [comment]
> Well, the main user of the library is dcs liberation and they use direct git commit to refer.

[Here's how](https://github.com/dcs-liberation/dcs_liberation/blob/9a1860fc5e752eaaae966efc81387f2d828157fa/requirements.txt#L35), in case you want to do the same.

**Comment by wrycu** [comment]
@rp- or @DanAlbert in the meantime, can you cut a new release?

**Comment by DanAlbert** [comment]
I can't.

**Comment by rp-** [comment]
I would wait till #280 is merged and then do a release.

**Comment by rp-** [comment]
sorry took a while, but finally 0.14.0
