### ISSUE TITLE
RFC: drop python 3.7 support

### ISSUE THREAD

**Issue by DanAlbert** [pydcs/dcs#299]
Python 3.8 adds `functools.cached_property` which would be nice for cleaning up some lazily initialized globals like `PayloadDirectories` and probably `LiveryScanner`.

Is anyone still relying on 3.7 support? That version of Python is EOL in about a month and a half, so I hope not.

**Comment by mkosmo** [comment]
Python 3.7 goes EoL in less than a month ([2023-06-27](https://devguide.python.org/versions/)).  I'd recommend keeping ahead of the python support schedule.

**Comment by DanAlbert** [comment]
No one seems to mind and I want `typing.Literal` for https://github.com/pydcs/dcs/pull/326, so will send a PR for this momentarily.
