### ISSUE TITLE
Is the test script 'war.py' a WIP?

### ISSUE THREAD

**Issue by ghost** [pydcs/dcs#3]
So far all the test scripts (destroy_oil_transport.py, dogfight_wwii,py, random_mission.py) work with no problems, but war.py is giving some errors:

```
Traceback (most recent call last):
  File "C:\Users\randl\AppData\Local\Programs\Python\Python36-32\Lib\site-packages\dcs\scripts\war.py", line 300, in <module>
    sys.exit(main())
  File "C:\Users\randl\AppData\Local\Programs\Python\Python36-32\Lib\site-packages\dcs\scripts\war.py", line 222, in main
    m.load_file("C:\\Users\\peint\\Saved Games\\DCS\\Missions\\dcscs_setup\\warehouse.miz")
  File "C:\Users\randl\AppData\Local\Programs\Python\Python36-32\lib\site-packages\dcs\mission.py", line 234, in load_file
    with zipfile.ZipFile(filename, 'r') as miz:
  File "C:\Users\randl\AppData\Local\Programs\Python\Python36-32\lib\zipfile.py", line 1082, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\peint\\Saved Games\\DCS\\Missions\\dcscs_setup\\warehouse.miz'
```

I ask if it is a work in progress because it seems to be looking for a file on your computer, and by that I mean it isn't following a %PATH% type directory, but rather a fixed directory as seen in the username 'peint'

Beside this, wanted to ask if to your knowledge, is there an active group of members using this? I was surprised to see that the post in the ED forums had no replies. It seems to me that this project has great potential and I never see anything about it? There some reason for this or do you know that there are indeed people using this? 

I'm trying to learn more about it to make my own missions and would be nice if there was people on ED discussing this.. I'm working on making practice BVR missions for the F-15C, and possibly the Su-27/Su-33 if all goes well, that will randomize the starting location of the player and AI, and thinking it would be nice to be able to randomize the number of AI and their aircraft based on initial parameters (doesn't seem like this is implemented yet; things like arguments or variable skill level to change the output of the scripts without having to re-write lines of code) or more likely, re-writing specific lines of code. 

Is this possible in the current framework or would I need to insert snippets or custom code into the starting location part of the code that randomizes the starting x and y, and possibly even the z or altitude as I'm sure it is refereed to in the code.. I read in your first issue on github that you are busy so I didn't want bombard you with specific questions or even ask anything that wasn't bug related for the fact that you are busy and also because I am somewhat out of my league and don't feel in place to ask certain questions.

**Comment by rp-** [comment]
Hi!

The war.py is a work in progress/testbed for me and wasn't actually meant to be included, so as you noticed this will not work without the setup mission you are missing.

Well I honestly don't know why nobody is using or trying it, you seem to be the first who is interested at all, maybe none can program python or didn't really see the effort I put into this.
I'm not saying that this framework is perfect (it still has a lot of bugs and a few missing features) but you can already do a lot of crazy things.

Well what you want can already be done, you would just have to write your own mission creator, the test mission should actually already give you enough hints how to do it if you know how to program python.

Seeing your requirements you might be better of with a framework like MOOSE or MIST, but this works on a completely different level but except the randomized starting position can do the same and is a lot more used in the DCS community.

If you still want to play around and maybe try a bit of python development you could use the WWII script as a starting point, it's not very complex and already does vaguely what you want, except it uses WWII planes, but it might be a starting point for you.

For developing I recommend you pycharm(https://www.jetbrains.com/pycharm/) it has one of the best auto completions and comes in a free community version. I can help you with questions to the framework, but I guess teaching you python to is also a bit out of my league. (there are enough tutorials/courses on the internet)

So just feel free to ask question I will answer whatever I can.

**Comment by walterroach** [comment]
I can see the effort you've put in, and I'll definitely be using this and contributing what I can soon.  Good stuff rp-
