### ISSUE TITLE
Error loading mission file - FARP __init__ signature incorrect

### ISSUE THREAD

**Issue by Igneous01** [pydcs/dcs#30]
I get an error when trying to load an existing .miz file.

`
Traceback (most recent call last):
  File "C:/Users/U/PycharmProjects/dcs_dnd_campaign/test.py", line 4, in <module>
    successLoad = m.load_file('C:\\Users\\U\\Saved Games\\DCS\\Missions\\dcs_dnd_campaign\\testmission.miz')
  File "C:\Users\U\PycharmProjects\dcs_dnd_campaign\venv\lib\site-packages\dcs\mission.py", line 342, in load_file
    self.coalition[col_name].load_from_dict(self, imp_mission["coalition"][col_name])
  File "C:\Users\U\PycharmProjects\dcs_dnd_campaign\venv\lib\site-packages\dcs\coalition.py", line 173, in load_from_dict
    static = FARP(
TypeError: __init__() got an unexpected keyword argument '_type'
`

It seems as though the init signature for FARP is incorrect, or the code constructing it is wrong.
`
class FARP(Static):
    def __init__(self, unit_id=None, name=None, frequency=127.5, modulation=0, callsign_id=1):
        super(FARP, self).__init__(unit_id, name, "FARP")
        self.category = "Heliports"
        self.shape_name = "FARPS"
        self.heliport_frequency = frequency
        self.heliport_modulation = modulation
        self.heliport_callsign_id = callsign_id
        self.can_cargo = False
`

**Comment by rp-** [comment]
couldn't reproduce this, maybe you can provide me with your test mission

**Comment by Igneous01** [comment]
[test_mission.zip](https://github.com/pydcs/dcs/files/4568737/test_mission.zip)

Attached is my test mission (rename .zip to .miz)

**Comment by rp-** [comment]
loads with github master branch here, are you using the release version?
maybe it was already fixed, i'll probably do a new release with the next open beta update

**Comment by Igneous01** [comment]
I'm running v0.9.6, when I inspect the stack trace I see in coalition.py:173 an attempt to construct a FARP object with a _type argument. When I look at the __init__ method in unit.py:324 I see that _type is not part of the method signature which would explain the error i'm getting.

Although it sounds like I'm maybe running an older version? I installed through pip.
