### ISSUE TITLE
security policy?

### ISSUE THREAD

**Issue by DanAlbert** [pydcs/dcs#300]
@rp- I've found a security vulnerability. How should those be reported and handled?

If you want more detail, you can enable https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability so I can report it privately.

**Comment by rp-** [comment]
I think I enabled the private security reporting stuff now

**Comment by DanAlbert** [comment]
Yep, that worked. Filed.
