### ISSUE TITLE
AH-64D_BLK_II has no pylon 5

### ISSUE THREAD

**Issue by spencershepard** [pydcs/dcs#318]
From [DCS 2.8.5.40170 Open Beta changelog](https://www.digitalcombatsimulator.com/en/news/changelog/openbeta/2.8.5.40170/): "Added Internal Aux Fuel Tank option"

We now get this error:
Plane AH-64D_BLK_II has no pylon 5.

I tried using the export script but there were no changes to this helicopter, from my installation with latest open beta.  I must be missing something.

**Comment by spencershepard** [comment]
By the way, I'm happy to do the export and PR, I could just use some guidance on the procedure.

**Comment by DanAlbert** [comment]
https://github.com/pydcs/dcs/pull/315
