### ISSUE TITLE
Airport data export for Channel map

### ISSUE THREAD

**Issue by Khopa** [pydcs/dcs#36]
Hello, 

I've been trying to add support for the newly released "Channel" map. 

I figured out that the Python script **tools/airport_import.py** was to be used to generate the Python code representing the map and i found this comment : 

```
This script imports airport data, that was previously exported by a lua function.

The lua function to export is just beneath this comment block, insert it somewhere in the mission editor
and call it somewhere
```

The lua function being : 

```lua
function dumpairportdata()
    local S	= require('Serializer')
    local airdromedump = {}
    for k, v in base.pairs(MapWindow.listAirdromes) do
        --MapWindow.listAirdromes[unit.boss.route.points[1].airdromeId].roadnet
        local sList = Terrain.getStandList(v.roadnet, {"SHELTER","FOR_HELICOPTERS","FOR_AIRPLANES","WIDTH","LENGTH","HEIGHT"})
        info = {}
        info["airport"] = v
        info["standlist"] = sList
        airdromedump[k] = info
    end
    local f = base.io.open("C:\\tmp\\standlist.lua", 'w')
    if f then
            local s = S.new(f)
            s:serialize_simple2('airports', airdromedump)
            f:close()
    else
        showWarningMessageBox(_('Error saving standlist'))
    end
end
```

But I'm a bit confused about how to exactly use the lua script...

I first naively tried to add the lua script in a DoScript action in the Mission Editor, and then to call the function in a running mission. But this would not work as the code in this function does not look like it could be run from a running DCS mission script environment.

```
insert it somewhere in the mission editor and call it somewhere
```

After re-reading that, I figured out that the function probably has to be added to "<DCS>/MissionEditor/MissionEditor.lua" in DCS World files ?

But then, where do you usually call dumpairportdata() ? 

I've tried calling it from random location in the Mission Editor UI code (for instance when the briefing editor is opened for a mission), but at best i just managed to crash DCS on startup without error logs... 😩 So I'm probably missing something.

Could you clarify how to use this script ?
It would make me able to add support for new DCS maps in the future 😁.

Thanks, 

Khopa

**Comment by rp-** [comment]
Well, yes this isn't really good documented.

I think I had that function somewhere in the mission editor triggered whenever a unit formation was changed. Of course the map you want to export is the one currently loaded in the mission.

The last map that I exported was PersionGulf, so it might possible that ED added/removed some fields that now would break the export? Or maybe you don't have the `C:\tmp\` folder, because there the export data will be in the file `standlist.lua`.
But as far as I remember error have usually be logged to the default DCS `log.txt`

**Comment by rp-** [comment]
Just stroke my head, you also my have to allow the lua io module, otherwise you can't write to the filesystem:
it should be in the `DCS World/Scripts/MissionScripting.lua`
just comment the santize io line and it should work.

**Comment by Khopa** [comment]
Thanks for your help !

Through trial and error I finally managed to generate the export. 

Here is what i did for futher reference :

**Step 1 - Modify DCS Mission Editor Code**

In **<DCS>/MissionEditor/modules/me_map_window.lua** : 

I added the dumpairportdata function, just before the createAircraft function. And i added a call to dumpairportdata in the createAircraft function. It should look like this : 

![image](https://user-images.githubusercontent.com/2546901/84056618-c146b500-a9b6-11ea-9240-1132b07100ff.png)

So this generate the data export whenever an aircraft is added in the mission editor. 

**Step 2 - Launch DCS and open the mission editor, create a new mission on the Channel map (which i want to export)**
**Step 3 - Add a random aircraft on the map to trigger the dump**
**Step 4 - Retrieve the lua standlist file.**
**Step 5 - Run tools\airport_import.py -t <name_of_the_map> <path_to_your_standlist.lua_file>**
**Step 6 - Copy the stdout of the airport_import.py to a new python file in terrain/<name_of_the_map>.py**
**Step 7 - Add the necessary import at the beginning of the file:**

```python
import os

from dcs import mapping
from dcs.terrain import Airport, Runway, ParkingSlot, Terrain, MapView, Graph

```

**Step 8 - Complete the code at the end of the file, add a class before the self.airports calls that do not make sense on their own.**



TODO : figure out how to retrieve center of the map, temperature, default bullseye... etc


I'll try to complete the procedure, and will make a PR tonight before closing the issue.

**Comment by rp-** [comment]
center of map i think is in some lua file for the map.
bullseye i took from a simple map save from the editor. 
temperature us from my fantasy and climate data from Wikipedia from one of the cities of the map.

**Comment by Khopa** [comment]
Thanks ! 

There is a "MapCoords" file for the Caucasus map, but it isn't there for the others map.

For now, for the Channel map, i copied the temperature data from Normandy (it is probably close enough), and i retrieved the X,Y bounds and coordinates manually from the mission editor.

Bullseye seems to be set to 0,0 by default for this map.
