### ISSUE TITLE
Any way to convert x, y coordinates to MGRS with pydcs? 

### ISSUE THREAD

**Issue by Marcus9K720** [pydcs/dcs#38]
Thanks for the great project!
For I couldnt find better way to ask something about pydcs, I write here:

I want to convert dcs x,y coordinate to MGRS (or LL, LMS etc) but could not find class/method
DCS script engine has the [function ](https://wiki.hoggitworld.com/view/DCS_func_LLtoMGRS)but I want convert to MGRS along with pydcs

Any way to do it or even workaround?
Thanks in advance!

**Comment by rp-** [comment]
see https://github.com/pydcs/dcs/issues/17

**Comment by Marcus9K720** [comment]
Thanks! sorry didnt think of searching closed issues..

**Comment by Khopa** [comment]
If you guys have a code example on how to do this, i'd be interested. I have tried to play around with pyproj as suggested in #17  to convert DCS World X/Y coordinates to something meaningful, but without success.

Then from the DCS World files, it is possible to retrieve useful values for projection from the file 
 : <dcs>/Mods/terrains/Caucasus/Caucasus.MapCoords.py

But this is to convert Caucasus map coordinates only, and these values are hidden for others maps. (probably in <dcs>/Mods/terrain/<map name>/terrain.cfg.lua.pak.crypt) Maybe we can extract them somehow though.

So if someone manage to find a solution and the projection values for the others map, i think it could be great to share and have this built-in in pydcs in the future.

**Comment by Marcus9K720** [comment]
Currently I am thinking about invoking DCS script engine lua method (LLtoMGRS) to get what the converted coordinates, but it may be a long shot because I still dont know how to "require" DCS script engine functions from outside of DCS executable

I personally don't think real world, general solution like pyproj would work with DCS because DCS is so buggy... 
(i found [this site](http://www.movable-type.co.uk/scripts/latlong-utm-mgrs.html), maybe this can work too and easy to try it out because it works as online! )

(My) Last resort would be export coordinates as a small grids for the entire map (or at least parts that matters),  I saw one project did this yesterday but cannot find it again now. Dont want to do this really.
