### ISSUE TITLE
DCS export documentation

### ISSUE THREAD

**Issue by spencershepard** [pydcs/dcs#384]
I'd like to contribute exports to this repo or my own fork.  What's the basic procedure?  Thanks

**Comment by rp-** [comment]
Well just open a PR with the changes and we can discuss there than.

**Comment by spencershepard** [comment]
Hi @rp- , to be clear I'm asking for the export proceedure.  Is it as simple as following the comments in pydcs_export.lua?

**Comment by rp-** [comment]
ah, ok. Yes it is.
If there is some error while exporting, it is in the dcs.log file.

**Comment by spencershepard** [comment]
I discovered that we need the WWII assets pack installed before export.  Otherwise it looks like it's gone okay.  #389
