### ISSUE TITLE
[Question] forcefully removed trigger from m.triggerrules.triggers makes trigger load order randomly shuffled!

### ISSUE THREAD

**Issue by Marcus9K720** [pydcs/dcs#39]
EDIT: it turns out, sometimes when "loading"the .miz file, the load order of triggers shuffled up, from the start. so it has nothing to do with remove.
current workaround is m.triggerrules.triggers.sort(key= .. ), right after loading the miz file.

--- original post (*depricated*) 
I need to add/remove triggers in the miz file,
since there are no "remove_trigger" method, i removed some triggers by 

`m.triggerrules.triggers.remove(t)`

the trigger removed, then the triggers load order are all randomly re-ordered.
Any idea why this is happening, (or I am not even sure this is pydcs issues. maybe it's DCS who shuffles it?)
or proper way to add/remove triggers, or any workaround?

**Comment by rp-** [comment]
Well my first guess would be that this is a bug or not properly implemented :)
I'll check it as soon as I have time, or as always patches are welcome

**Comment by Marcus9K720** [comment]
I'm fine with .sort() for now, but i will try to make an reproducible miz file when i have time!

**Comment by Marcus9K720** [comment]
Ok. i managed to reproduce trigger shuffling,
now i am pretty sure that's because along the way of  reading / writing python <-> lua  somehow trigger order gets lost.,
because 1. reading miz -> 2. adding / removing trigger-> 3. write miz -> 4. (re) reading miz  -> 5. adding/removing...
and SO ON is what im doing right now

Most of the users will kinda only 1. read_miz 2.add trigger 3.save and that's over, I think i am the only one re-read written miz and repeat the process.

Anyway anyone can download the zip, run the .py file multiple times, and you will see the order of triggers changes.
If i can get manage more time, i will investigate the cause. Thanks

[Shuffle.zip](https://github.com/pydcs/dcs/files/4844001/Shuffle.zip)

**Comment by rp-** [comment]
I couldn't reproduce you described shuffle bug, but found another bug your mission shows.

If more than one trigger/dofile is using the same script file, it will only load the last resource key and ignore all other.

maybe you can create a small sample python script that will reproduce this issue with your mission.
Or attach a created shuffled mission, maybe I can see something out of the mission file

**Comment by Marcus9K720** [comment]
Sorry for late reply i was very busy with work.
I will explain step by step!

1. Unzip the files and run shuffleTriggerTest.py
2. You can see the triggers are ordered as set from the DCS mission editor. 
For the test purpose, I entered each trigger's comment as number equivalent of its trigger load order
![image](https://user-images.githubusercontent.com/60172213/86886332-b3a95a00-c131-11ea-82c1-c6ff5ec0d866.png)
like this. the script prints the comment of each triggers, ordered as read by pydcs

3. run the script(shuffleTriggerTest.py) a few times. You will see the order of the triggers are chainging like this
![image](https://user-images.githubusercontent.com/60172213/86886508-097e0200-c132-11ea-9275-12e4e1a016dc.png)
<- ran 2nd time. this is normal

![image](https://user-images.githubusercontent.com/60172213/86886615-37fbdd00-c132-11ea-95f7-804fd7ff8ec0.png)
<- ran 3rd time. original tiggers are ok, but new trigger randomly placed between original triggers. this may related with what @rp- said in the previous comment

![image](https://user-images.githubusercontent.com/60172213/86886735-6a0d3f00-c132-11ea-9909-d855466a9da3.png)
<-ran about 7-8th time. now it's almost random

I ended up writing comments something like "0_MOOSE" .. "1_MYFIRSTLUA", "2_MY2NDLUA" and used .sort(key= lambda x: x.comment). it works for now ^^

I will try to look into the root cause if I can. Anyway hope this helps.

**Comment by rp-** [comment]
Can't see the shuffleTriggerTest.py file?

**Comment by Marcus9K720** [comment]
Sorry somehow the .py got lost while ziping. -_-;;  Re-zipped and uploaded!
[Shuffle_re.zip](https://github.com/pydcs/dcs/files/4910338/Shuffle_re.zip)

**Comment by rp-** [comment]
I could now reproduce and fix this issue: f787e61
