### ISSUE TITLE
Missing some Nevada airport / data in Nevada.py

### ISSUE THREAD

**Issue by victorcotap** [pydcs/dcs#4]
Hi 👋

Thanks for putting in the work and mapping the mission file into a more actionable format!

I've been trying to get some of our missions parsed by the lib, both on 1.5 and 2.1 and I'm getting some issues.
Some of it I've been able to fix myself as pydcs is simply looking for keys that do not seem to exist in 2.1 anymore in the mission file so I skip them ( `used/needModules` for example).
Still I'm getting to the point where I realize that some of the airports in our warehouse file are simply not present in the `Nevada.py` file. Even with adding a condition to ignore any airport not present in that file, when trying to assign parking spots to units, it seems like some are missing as well.

I'm fairly new to this so I'm simply wondering if it's just because the newest Nevada terrain data hasn't been extracted into Nevada.py or if I'm looking at this from a wrong angle.

**Comment by rp-** [comment]
Hi!

Yes, I didn't do any work on pydcs since I while and you are right there will be probably a lot of problems with mission file update and I did not update the nevada with the new airports. I can run the export script this evening(CEST) and update to the latest nevada theater and maybe fix some of the mission file problems.

**Comment by rp-** [comment]
Ok, I have done a new export of nevada(1b6439a2bcd634470c6fc19765b3febf0df26475) with all new airports and fixed the needModules key error(2d9daa9db88a5f8ecf88da5e2bbe686f6a62c5ae).
I was able to load and save a very simple 1 flight mission, hope that gets you started.

**Comment by victorcotap** [comment]
I'll look into it when I have a chance, thanks for your prompt response!
