### ISSUE TITLE
Parsing of mission fails when referenced resources are not included in the mission

### ISSUE THREAD

**Issue by wrycu** [pydcs/dcs#42]
I've downloaded a few missions where files are mentioned in `mapResource` but not included in the mission itself.  No error checking is done to handle the file not existing.  I've included an example mission for reference.

[[Coop]_OP_Custodia_v1.zip](https://github.com/pydcs/dcs/files/4916513/Coop._OP_Custodia_v1.zip)

https://github.com/pydcs/dcs/blob/master/dcs/mission.py#L252

**Comment by rp-** [comment]
This mission uses a very old format.
I made a bunch of fixes to be able to load it, but even DCS drops a lot of plane groups,
but neverless a few fixes that should also help some other missions to load.
And I was reminded that task options are not completed yet.

**Comment by wrycu** [comment]
Thank you, sir.

**Comment by wrycu** [comment]
@rp- I pulled the latest commit and this still happens. Line 236 (https://github.com/pydcs/dcs/blob/master/dcs/mission.py#L236) triggers it.

**Comment by wrycu** [comment]
[(CFH_MISSION)_C130_ESCORT_V3.zip](https://github.com/pydcs/dcs/files/4944103/CFH_MISSION._C130_ESCORT_V3.zip)

Here's the mission, since I realize I uploaded a different one before.

**Comment by wrycu** [comment]
@rp- this is still an issue in 0.9.9. Any chance you can extend your previous fix to other lines where the same action is taken, e.g. 236 (linked above)?

**Comment by wrycu** [comment]
Actually, reviewing the error, it looks like the remaining issue is more in depth. I'll start looking into it and file a new issue if I can come up with a relatively simple fix.
