### ISSUE TITLE
Parsing fails when neutrals not included

### ISSUE THREAD

**Issue by wrycu** [pydcs/dcs#43]
I'm trying to parse a mission which doesn't have the "neutrals" role filled out and get a keyerror as a result.  I think if the key is not there, the value should be initialized to 0 (or set to `None`.) 

I've attached a sample mission and the relevant code is [here](https://github.com/pydcs/dcs/blob/master/dcs/groundcontrol.py#L34).

[[UH-1H]_Forestry_Operations.zip](https://github.com/pydcs/dcs/files/4916571/UH-1H._Forestry_Operations.zip)

**Comment by rp-** [comment]
fixed: 6803fd718ef1b504399b3d2035e430ccd13384eb
