### ISSUE TITLE
KeyError: 'speed'

### ISSUE THREAD

**Issue by wrycu** [pydcs/dcs#47]
Looks like the trigger for checking if a unit speed is above a certain value isn't properly being parsed.  Given that I assume this has worked in the past, it may be worth catching the keyerror and trying to read the other key instead. Two random missions I tested with this were versions 14 and 17.

https://github.com/pydcs/dcs/blob/master/dcs/condition.py#L1147 (probably also happens on Lower, but I didn't test that)

Attached mission - [LUNA.zip](https://github.com/pydcs/dcs/files/4922959/LUNA.zip)

**Comment by rp-** [comment]
Seems this was never correct and it always has been "speedU".

fixed.
