### ISSUE TITLE
Formation Task is not implemented

### ISSUE THREAD

**Issue by wrycu** [pydcs/dcs#48]
The Formation task results in a keyerror (`5`), as it appears to not be implemented.

https://github.com/pydcs/dcs/blob/master/dcs/task.py#L20

[HB Kish Kat Attack Coop 8 - 4 crew..zip](https://github.com/pydcs/dcs/files/4923036/HB.Kish.Kat.Attack.Coop.8.-.4.crew.zip)

The `SEAD2` flight has the task assigned to it (along with all of the groups at the same airport.)

**Comment by rp-** [comment]
is part of the Options #44
