### ISSUE TITLE
A number of additional tasks are not implemented

### ISSUE THREAD

**Issue by wrycu** [pydcs/dcs#49]
The following tasks are not implemented:
- `Silence` (key: 7)
- `Restrict Afterburner` (key: 16)
- `Radio Usage When Contact` (key: 21)
- `ECM using` (key: 13)
- `Chaff / Flare using` (key: 4)

I haven't gone through yet to determine what the tasks are, but also:
- key: 0

**Comment by rp-** [comment]
duplicate #44
