### ISSUE TITLE
Various airports missing from Normandy

### ISSUE THREAD

**Issue by wrycu** [pydcs/dcs#50]
Attempting to parse a Normandy mission results in `AttributeError: 'NoneType' object has no attribute 'load_from_dict'`.

After looking through the code and map, the following airports are missing:
- Conches
- Argentan
- Goulet
- Vrigny
- Essay
- Hauterive
- Barville

You can reproduce by saving any mission on the Normandy map, but just in case, here's one anyway.
[normandy.zip](https://github.com/pydcs/dcs/files/4933457/normandy.zip)

**Comment by Khopa** [comment]
I made a new airport dump for Normandy. 
See https://github.com/pydcs/dcs/pull/52

But i'm still worried about possible compatibility issues since they changed one of the airport name in game. Hopefully it won't cause any issues.
