### ISSUE TITLE
Parking parsing is sometimes messed up

### ISSUE THREAD

**Issue by wrycu** [pydcs/dcs#51]
I'm not sure why, but sometimes the "start from ramp" positions of units are messed up, causing `AttributeError: 'NoneType' object has no attribute 'unit_id'`.  Loading the mission in the mission editor shows the correct number on the unit, but the preview is often in the wrong spot.

Here's the relevant code: https://github.com/pydcs/dcs/blob/master/dcs/coalition.py#L112

Via debugging, it appears that `plane.parking_id` returns the correct value (19 in the case of the attached mission), while `plane.parking` returns an invalid space (121).

Note that although this mission is version 14, I've seen it happen with version 16 as well.

Ironically named example mission:
[No Room for Error.zip](https://github.com/pydcs/dcs/files/4933661/No.Room.for.Error.zip)

**Comment by Khopa** [comment]
There is something weird with this mission, it must be very old.

For me, on mission load, in the DCS mission editor, the 4 viggens appears on parking slots 19, 18, 20, 24. 
But in the panel on the right, they are set up on parking slot 01,02,03,04

See :
![image](https://user-images.githubusercontent.com/2546901/87735041-a09f2580-c7d4-11ea-8e41-21874226da5c.png)

Then if you save the mission or drag the viggen around, they'll jump to slot 1,2,3,4

I haven't looked into the file format, but I'd say that the slot logic has changed, so DCS default them to the first available slot. 

A similar logic could maybe be implemented in pydcs as a fallback mechanism.

**Comment by Khopa** [comment]
Sorry kind of misunderstood the issue. I'm not sure whether you are encountering the issue on miz laod, or if the loaded data is incorrect ?

Where do you encounter the issue exactly ? 

(I do not have the error when i load the mission file (unmodified).)

My code : 

```
    def test_load_no_room_error(self):
        test_mission_folder = os.path.join(os.path.dirname(__file__), 'missions')
        m = dcs.mission.Mission()
        self.assertTrue(m.load_file(os.path.join(test_mission_folder, "No Room for Error.miz")))

        group = m.country("Georgia").find_group("Bolt 1")
        print(group)

        print("Parking Index :")
        print(group.units[0].parking)
        print(group.units[1].parking)
        print(group.units[2].parking)
        print(group.units[3].parking)

        print("Parking IDs :")
        print(group.units[0].parking_id)
        print(group.units[1].parking_id)
        print(group.units[2].parking_id)
        print(group.units[3].parking_id)

        print("Parking Slot objects :")
        print(m.terrain.senaki_kolkhi().parking_slot(group.units[0].parking))
        print(m.terrain.senaki_kolkhi().parking_slot(group.units[1].parking))
        print(m.terrain.senaki_kolkhi().parking_slot(group.units[2].parking))
        print(m.terrain.senaki_kolkhi().parking_slot(group.units[3].parking))

```
Output : 
```
Mission file is using an old format, be aware!
Parking slot id '121' for 'Bolt 1' on airport 'Senaki-Kolkhi' not valid, placing on next free
Parking slot id '90' for 'Bolt 1' on airport 'Senaki-Kolkhi' not valid, placing on next free
Parking slot id '83' for 'Bolt 1' on airport 'Senaki-Kolkhi' not valid, placing on next free
Parking slot id '82' for 'Bolt 1' on airport 'Senaki-Kolkhi' not valid, placing on next free
Group: Bolt 1
Parking Index :
14
15
16
17
Parking IDs :
06
07
08
09
Parking Slot objects :
ParkingSlot(14, "06", large=False, heli=False)
ParkingSlot(15, "07", large=False, heli=False)
ParkingSlot(16, "08", large=False, heli=False)
ParkingSlot(17, "09", large=False, heli=False)
```

**Comment by wrycu** [comment]
Hmm. I have the latest version (the released version, not the latest commits) and just load the mission, resulting in the following stacktrace:

```python
Mission file is using an old format, be aware!
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2020.1.3\plugins\python\helpers\pydev\pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2020.1.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/w/PycharmProjects/leetsaber/misc/async.py", line 304, in <module>
    m_data = parser.parse_mission(mission)
  File "C:\Users\w\PycharmProjects\leetsaber\misc\t_dcs.py", line 839, in parse_mission
    self.msn.load_file(str(mission_name))
  File "C:\Users\w\PycharmProjects\leetsaber\venv\lib\site-packages\dcs\mission.py", line 355, in load_file
    self.coalition[col_name].load_from_dict(self, imp_mission["coalition"][col_name])
  File "C:\Users\w\PycharmProjects\leetsaber\venv\lib\site-packages\dcs\coalition.py", line 112, in load_from_dict
    plane.set_parking(slot)
  File "C:\Users\w\PycharmProjects\leetsaber\venv\lib\site-packages\dcs\unit.py", line 125, in set_parking
    parking_slot.unit_id = self.id
AttributeError: 'NoneType' object has no attribute 'unit_id'
```

**Comment by rp-** [comment]
Yeah I said, I fixed some issues with old missions and one of them was with invalid parking id's(since they changed the format).
So now if the id isn't valid it will be placed in the next free slot of the airport.

Btw. I'm not to much into, trying to load all old missions versions, if it is a simple fix, then ok.
But I'm certainly not going to implement a full mission converter or specific version loader, my recommendation would then be
to just resave the mission in DCS, but in most cases it will be broken anyway, because DCS seems also to not give to much
about mission compatibility.

**Comment by wrycu** [comment]
That's fine. I just recently grabbed all of the missions off of the ED site and I'm trying to create a database of them... but only a very small percentage (<10%) actually parsed.

**Comment by wrycu** [comment]
Looks like it's been fixed. Closing.
