### ISSUE TITLE
KeyError: 'FAC_AttackGroup'

### ISSUE THREAD

**Issue by wrycu** [pydcs/dcs#58]
It looks like sometimes a unit task can be set to `FAC_AttackGroup` (`FAC - Assign Group` in the mission editor), which is not a defined task in pydcs (though `FAC_EngageGroup` is.)

https://github.com/pydcs/dcs/blob/a5ace97ed1b13f56f8ec20e569a30898ec5f2e3b/dcs/task.py#L27

```python
tasks_map.keys()
dict_keys(['ControlledTask', 'Escort', 'AttackGroup', 'Bombing', 'BombingRunway', 'EngageTargetsInZone', 'EngageGroup', 'EngageUnit', 'AWACS', 'Refueling', 'Tanker', 'Orbit', 'Follow', 'Aerobatics', 'FAC', 'FAC_EngageGroup', 'Hold', 'Land', 'Embarking', 'EmbarkToTransport', 'DisembarkFromTransport', 'CargoTransportation', 'EWR', 'GoToWaypoint', 'FireAtPoint'])
```

Example mission below - relevant unit is ID 128.
[desert_creechure_Harrier.zip](https://github.com/pydcs/dcs/files/4978272/desert_creechure_Harrier.zip)

**Comment by ColinM9991** [comment]
This issue is now resolved.
