### ISSUE TITLE
Minor error in presented sample

### ISSUE THREAD

**Issue by Flupke25** [pydcs/dcs#6]
Hello,

AWACS position should be Batumi.position.x and Batumi.position.y in the sample. To make it complete, imports should also be added. Otherwise, it works pertfectly :) Thank you very much for the efforts and the great tool you made, I enjoy it a lot to create very easily random and globally consistent missions!

Flupke.

**Comment by rp-** [comment]
Fixed 67fbd54fa962b2408d292e6fc8d3b56511411580
