### ISSUE TITLE
'gbk' codec can't decode byte 0x80 in position 392: illegal multibyte sequence

### ISSUE THREAD

**Issue by edilyxin** [pydcs/dcs#77]
hi gays
I‘m your fans!
I encountered such a problem when I ran the test program, as long as I added any group, call these methods when (for example :m.awacs_flight(...)) will report such an error, it is estimated that the underlying read and write file problem, may I ask how to solve?
![alt:error image](https://img03.sogoucdn.com/app/a/100520146/d8ceb7e53e9f7f365a5da27e0289c6ed)

**Comment by edilyxin** [comment]
my dev environment:    python 3.7  
os  : windows10
dev tools:  vscode 1.4

**Comment by rp-** [comment]
should be fixed by #78
