### ISSUE TITLE
Only helicopter parking spots allowed for some airports?

### ISSUE THREAD

**Issue by DanAlbert** [pydcs/dcs#82]
https://github.com/pydcs/dcs/blob/c12733a4712e802b41fd26ad8df7475d06c334b3/dcs/terrain/terrain.py#L209

This restricts helicopters to being parked _only_ in helicopter specific parking spots. Airports using the other parking resolution method are allowed to park helicopters in other spots: https://github.com/pydcs/dcs/blob/c12733a4712e802b41fd26ad8df7475d06c334b3/dcs/terrain/terrain.py#L194

Could be that `=` was intended to be `+=`, but I'm not sure why there are two different resolution methods so perhaps there's a reason for this? The result is that airports like Bandar Lengeh cannot have helicopters parked at them.

**Comment by rp-** [comment]
v1 was for the old terrain format(before caucasus update) if I remember correctly it shouldn't be used anymore.

And if it is possible to place helicopters on Bandar Lengeh, then it is a bug, and we should check what conditions are used
to allow helicopters on what slot

**Comment by rp-** [comment]
So I tried to place helicopters on Bandar Lengeh and it isn't possible in the mission editor, so it is a DCS limitation

**Comment by DanAlbert** [comment]
Interesting. Thanks for confirming (and sorry for disappearing, got way sidetracked)
